### ISSUE TITLE
EPIC: Post Searching

### ISSUE THREAD

**Issue by mattthughes** [mattthughes/souls-like-gallery-app#3]
As a **site user** I can **search for posts to view posts that other users have posted** so that **I can find new posts I haven't seen**

Potential User Stories

- [x] Search by Post Name

- [x] Search by User name

- [x]  Search by Keyword

- [ ] Sort by Popularity
