### ISSUE TITLE
EPIC: User Profile

### ISSUE THREAD

**Issue by mattthughes** [mattthughes/souls-like-gallery-app#5]
As a **site user** I can **Create, read and update my profile** so that **I can log into my account, keep my information secure**

Potential User Story:

- [x] Create an account
- [x] Update username
- [x] Update Profile Picture
- [x] Change Password
- [ ] Reset Password if I have forgot it
