### ISSUE TITLE
EPIC: React Project Setup

### ISSUE THREAD

**Issue by mattthughes** [mattthughes/souls-like-gallery-app#6]
As a **developer** I can **deploy the site** so that **I can make sure the development project and the deployed project work as intended**

- [x] install React and supporting Libraries
- [x] Create base component
- [x] Early Deployment to Heroku
